name: EAS Build - Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: { node-version: 18.x }

      - run: npm ci

      - run: npm install -g eas-cli

      - name: Build APK (apk-testing)
        run: eas build --platform android --non-interactive --profile apk-testing
        env:
          EXPO_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}

      # Optional: Production AAB
      #- name: Build AAB (production)
      #  run: eas build --platform android --non-interactive --profile production
      #  env:
      #    EXPO_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}
